---
common:

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
.gitpod.Dockerfile:
  unmanaged: true
.gitpod.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
Rakefile:
  changelog_user: "puppetlabs"
  changelog_since_tag: 'v7.1.0'
spec/default_facts.yml:
  extra_facts:
    pe_server_version: '2019.8.6'
    puppet_metrics_collector:
      have_systemd: true
.rubocop.yml:
  default_configs:
    "RSpec/NamedSubject":
       Enabled: False
    "Style/ClassAndModuleChildren":
       Enabled: False
    "Style/LineEndConcatenation":
       Enabled: False
    "Lint/AssignmentInCondition":
       Enabled: False
    "Lint/RescueException":
       Enabled: False
    "Lint/UnderscorePrefixedVariableName":
       Enabled: False
    "Lint/UselessAssignment":
       Enabled: False
    "Style/Documentation":
       Enabled: False
    "Style/GlobalVars":
       Enabled: False
    "Style/GuardClause":
       Enabled: False
    "RSpec/EmptyExampleGroup":
       Enabled: False
    "Style/CollectionMethods":
       Enabled: False
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      version: '= 1.16.0'
    - gem: nio4r
      version: '=2.5.8'
